version: '3.8'

services:
  web:
    build: .
    container_name: web_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
    driver: local

networks:
  default:
    driver: bridge

