<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quadro com Quadrados</title>
    <style>
        body, html {
            height: 100%;
            margin: 0;
            font-family: Arial, sans-serif;
        }
        .header {
            color: white;
            position: relative;
            height: 57px;
            width: 100%;
            display: flex;
            justify-content: center; 
            align-items: center; 
            background-color: #004085;
            padding-right: 20px;
        }
        .quadro {
            background-color: #E8F8FF;
            border-radius: 8px;
            width: 95%;
            max-width: 1600px;
            height: 80%;
            max-height: 600px;
            border: 1px solid #ccc;
            overflow-y: auto;
            padding: 10px;
            margin-top: 100px;
            margin: auto;
            display: flex;
            flex-wrap: wrap;
            gap: 45px;
        }
        .card {
            width: calc(25% - 40px); 
            height: 200px; 
            background-color: #f0f0f0;
            border: 1px solid #ccc;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 18px;
        }
        .favoritos-container {
            color: white;
            position: relative;
            height: 57px;
            width: 100%;
            display: flex;
            justify-content: right; 
            align-items: center; 
            background-color: white;
        }
        .favoritos-button {
            top: 103px;
            margin-right: 20px;
            background-color: #004085;
            color: white;
            padding: 7px 22px;
            border: none;
            border-radius: 7px;
            cursor: pointer;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
            transition: background-color 0.3s;
        }
        .fixed-adicionar {
            position: fixed;
            top: 550px;
            right: 80px;
            z-index: 1800;
            background-color: lightblue;
            color: white;
            padding: 7px 22px;
            border: none;
            border-radius: 7px;
            cursor: pointer;
            text-align: center;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
            transition: background-color 0.3s;
        }
        .fixed-adicionar:hover {
            background-color: #e0a800;
        }
        .favoritos-button:hover {
            background-color: #e0a800;
        }
    </style>
</head>
<body>
    <div class="container-fluid p-0">
        <div class="header text-center">
            <h1 class="my-4">Biblioteca de livros</h1>
        </div>
    </div>
    <div class="favoritos-container">
        <button class="favoritos-button" onclick="window.location.href='/favorites'">Favoritos</button>
    </div>
    <div class="quadro" id="meuQuadro">
        <button class="fixed-adicionar" onclick="window.location.href='/add'">Adicionar</button>

        <!-- Aqui serão adicionados os quadrados -->
    </div>

    <script>
        // Função para adicionar os 16 quadrados
        function adicionarQuadrados() {
            var quadro = document.getElementById('meuQuadro');
            for (var i = 1; i <= 16; i++) {
                var quadrado = document.createElement('div');
                quadrado.className = 'card';
                quadrado.textContent = i;
                quadro.appendChild(quadrado);
            }
        }

        // Chama a função para adicionar os quadrados ao carregar a página
        adicionarQuadrados();
    </script>
</body>
</html>